import type { LearningActivity } from "./learning";

export const M2_ACTIVITY_LIBRARY: LearningActivity[] = [
  // 中文：倾听表达、故事理解、关系配对与生活分类
  {
    id: "cn-rhyme-cat-bag-m2",
    domain: "chinese", kind: "listen_choose", skillId: "cn.listen.rhyme", difficulty: 1, ageBand: "30-36m", variantCount: 3,
    title: "小猫找押韵朋友", skill: "感受相近尾音", instruction: "“小猫”的“猫”，和谁听起来像好朋友？",
    spokenInstruction: "小猫，喵喵，背上书包。听一听，小猫的猫，和书包的包，尾巴听起来很像。请找到书包。",
    speechLang: "zh-CN",
    choices: [
      { id: "bag-rhyme", label: "书包", icon: "box", color: "yellow" },
      { id: "dog-rhyme", label: "小狗", icon: "dog", color: "coral" },
      { id: "bus-rhyme", label: "公交车", icon: "bus", color: "blue" },
    ],
    answerId: "bag-rhyme", hint: "再听一遍：猫，包。最后都能听到“ao”。", successText: "猫、包，声音尾巴碰到一起啦！", parentTip: "生活里随口玩“猫—包、鸟—桥”声音接龙。", interests: ["animals", "vehicles"],
  },
  {
    id: "cn-two-step-builder-m2",
    domain: "chinese", kind: "sequence_3", skillId: "cn.listen.two-step", difficulty: 2, ageBand: "36-42m", variantCount: 3,
    title: "工程队听两步指令", skill: "理解动作顺序", instruction: "先修桥，再让汽车通过",
    spokenInstruction: "工程队注意。先拿小锤子修好桥，再让汽车开过去，最后回到小屋休息。把顺序排好吧。",
    speechLang: "zh-CN",
    choices: [
      { id: "hammer-first", label: "修桥", icon: "hammer", color: "yellow" },
      { id: "car-next", label: "汽车通过", icon: "car", color: "coral" },
      { id: "home-last", label: "回家", icon: "house", color: "green" },
    ],
    answerId: "hammer-first", hint: "先修好桥，汽车才能开，最后再回家。", successText: "听懂两步指令，工程任务完成！", parentTip: "日常给出“先拿杯子，再放桌上”的两步指令。", interests: ["construction", "vehicles"],
    interaction: {
      targets: [
        { id: "order-one", label: "先", color: "yellow" }, { id: "order-two", label: "再", color: "coral" }, { id: "order-three", label: "最后", color: "green" },
      ],
      correctTargets: { "hammer-first": "order-one", "car-next": "order-two", "home-last": "order-three" },
    },
  },
  {
    id: "cn-opposites-memory-m2",
    domain: "chinese", kind: "memory_pairs", skillId: "cn.vocabulary.opposites", difficulty: 2, ageBand: "36-42m", variantCount: 3,
    title: "反义词翻翻乐", skill: "理解相反概念", instruction: "翻开卡片，找到三对反义词",
    spokenInstruction: "大和小，长和短，开心和难过，它们都是相反的好朋友。一次翻两张，把三对朋友找出来。",
    speechLang: "zh-CN",
    choices: [
      { id: "op-big", label: "大", icon: "dinosaur", color: "green", visualScale: "large" }, { id: "op-small", label: "小", icon: "dinosaur", color: "yellow", visualScale: "small" },
      { id: "op-long", label: "长", icon: "long", color: "blue" }, { id: "op-short", label: "短", icon: "short", color: "coral" },
      { id: "op-happy", label: "开心", icon: "happy", color: "yellow" }, { id: "op-sad", label: "难过", icon: "sad", color: "purple" },
    ],
    answerId: "op-big", hint: "想一想，和“大”相反的是“小”。", successText: "三对相反朋友都找到了！", parentTip: "用家里的大勺小勺、长袜短袜继续玩。", interests: ["dinosaurs", "animals"],
    interaction: { correctTargets: { "op-big": "size", "op-small": "size", "op-long": "length", "op-short": "length", "op-happy": "feeling", "op-sad": "feeling" } },
  },
  {
    id: "cn-animal-home-memory-m2",
    domain: "chinese", kind: "memory_pairs", skillId: "cn.vocabulary.relationship", difficulty: 1, ageBand: "30-36m", variantCount: 3,
    title: "动物的家翻翻乐", skill: "建立事物关系", instruction: "帮动物找到自己的家",
    spokenInstruction: "小鸟住在树上，小鱼游在水里，小狗住在小屋旁。翻两张卡，帮动物找到家。",
    speechLang: "zh-CN",
    choices: [
      { id: "home-bird", label: "小鸟", icon: "bird", color: "yellow" }, { id: "home-tree", label: "树上", icon: "tree", color: "green" },
      { id: "home-fish", label: "小鱼", icon: "fish", color: "blue" }, { id: "home-water", label: "水里", icon: "waves", color: "blue" },
      { id: "home-dog", label: "小狗", icon: "dog", color: "coral" }, { id: "home-house", label: "小屋", icon: "house", color: "cream" },
    ],
    answerId: "home-bird", hint: "谁会飞到树上？谁会游进水里？", successText: "动物们都回到温暖的家啦！", parentTip: "散步时聊聊看到的动物住在哪里。", interests: ["animals", "nature"],
    interaction: { correctTargets: { "home-bird": "bird-home", "home-tree": "bird-home", "home-fish": "fish-home", "home-water": "fish-home", "home-dog": "dog-home", "home-house": "dog-home" } },
  },
  {
    id: "cn-rainy-day-predict-m2",
    domain: "chinese", kind: "story_choice", skillId: "cn.story.predict", difficulty: 1, ageBand: "30-36m", variantCount: 3,
    title: "乌云来了以后", skill: "根据线索预测", instruction: "乌云越来越多，接下来可能发生什么？",
    spokenInstruction: "天空的乌云越聚越多，风也吹起来了。豆豆龙抬头看看，接下来最可能发生什么呢？",
    speechLang: "zh-CN",
    choices: [
      { id: "rain-next", label: "下雨", icon: "cloud", color: "blue" }, { id: "sleep-next", label: "睡觉", icon: "bed", color: "purple" }, { id: "banana-next", label: "长香蕉", icon: "banana", color: "yellow" },
    ],
    answerId: "rain-next", hint: "乌云和风常常会把小雨点带来。", successText: "你从乌云里猜到了接下来的故事！", parentTip: "共读时在翻页前问一句“接下来会怎样”。", interests: ["nature", "dinosaurs"],
    interaction: { storyText: ["天空慢慢暗下来。", "乌云越聚越多。", "风把树叶吹得摇啊摇。"] },
  },
  {
    id: "cn-share-ball-story-m2",
    domain: "chinese", kind: "story_choice", skillId: "cn.story.social", difficulty: 1, ageBand: "30-36m", variantCount: 3,
    title: "只有一个皮球", skill: "理解轮流与分享", instruction: "两位伙伴都想玩皮球，怎么办？",
    spokenInstruction: "小兔和小狗都想玩同一个皮球。抢来抢去会不开心。它们可以怎么做呢？",
    speechLang: "zh-CN",
    choices: [
      { id: "take-turns", label: "轮流玩", icon: "ball", color: "green" }, { id: "hide-ball", label: "藏起来", icon: "box", color: "purple" }, { id: "angry-ball", label: "生气抢", icon: "angry", color: "coral" },
    ],
    answerId: "take-turns", hint: "一个人玩一会儿，再换另一个人。", successText: "轮流玩，两个伙伴都开心！", parentTip: "家庭游戏中使用“你一次、我一次”的固定说法。", interests: ["animals"],
    interaction: { storyText: ["小兔发现一个皮球。", "小狗也跑过来了。", "它们都想玩一玩。"] },
  },
  {
    id: "cn-tools-food-sort-m2",
    domain: "chinese", kind: "drag_sort", skillId: "cn.vocabulary.categories", difficulty: 2, ageBand: "36-42m", variantCount: 3,
    title: "工具和食物分队", skill: "按用途分类", instruction: "把能吃的和能修东西的分开",
    spokenInstruction: "苹果、香蕉和鸡蛋是食物。锤子、扳手和刷子是工具。把它们送到两支队伍里。",
    speechLang: "zh-CN",
    choices: [
      { id: "tf-apple", label: "苹果", icon: "apple", color: "coral" }, { id: "tf-banana", label: "香蕉", icon: "banana", color: "yellow" }, { id: "tf-egg", label: "鸡蛋", icon: "egg", color: "cream" },
      { id: "tf-hammer", label: "锤子", icon: "hammer", color: "blue" }, { id: "tf-wrench", label: "扳手", icon: "wrench", color: "green" }, { id: "tf-brush", label: "刷子", icon: "paintbrush", color: "purple" },
    ],
    answerId: "tf-apple", hint: "能吃进肚子的是食物，能帮忙做事的是工具。", successText: "两支队伍分得清清楚楚！", parentTip: "整理物品时请孩子说出“能吃的”和“不能吃的”。", interests: ["construction", "nature"],
    interaction: {
      targets: [{ id: "food-team", label: "食物", icon: "apple", color: "yellow" }, { id: "tool-team", label: "工具", icon: "wrench", color: "blue" }],
      correctTargets: { "tf-apple": "food-team", "tf-banana": "food-team", "tf-egg": "food-team", "tf-hammer": "tool-team", "tf-wrench": "tool-team", "tf-brush": "tool-team" },
    },
  },
  {
    id: "cn-sky-water-land-sort-m2",
    domain: "chinese", kind: "drag_sort", skillId: "cn.vocabulary.habitat", difficulty: 2, ageBand: "36-42m", variantCount: 3,
    title: "天空水里和地面", skill: "理解三类生活环境", instruction: "把伙伴送到天空、水里和地面",
    spokenInstruction: "小鸟飞在天空，小鱼游在水里，小狗和汽车跑在地面。把它们送到合适的地方。",
    speechLang: "zh-CN",
    choices: [
      { id: "world-bird", label: "小鸟", icon: "bird", color: "yellow" }, { id: "world-rocket", label: "火箭", icon: "rocket", color: "coral" },
      { id: "world-fish", label: "小鱼", icon: "fish", color: "blue" }, { id: "world-ship", label: "轮船", icon: "ship", color: "blue" },
      { id: "world-dog", label: "小狗", icon: "dog", color: "cream" }, { id: "world-car", label: "汽车", icon: "car", color: "green" },
    ],
    answerId: "world-bird", hint: "会飞的去天空，会游的去水里，会跑的留在地面。", successText: "天空、水里和地面都有伙伴啦！", parentTip: "出门时聊聊物体在天上、水里还是地面。", interests: ["animals", "vehicles", "space"],
    interaction: {
      targets: [{ id: "sky-team", label: "天空", icon: "cloud", color: "yellow" }, { id: "water-team", label: "水里", icon: "waves", color: "blue" }, { id: "land-team", label: "地面", icon: "stone", color: "green" }],
      correctTargets: { "world-bird": "sky-team", "world-rocket": "sky-team", "world-fish": "water-team", "world-ship": "water-team", "world-dog": "land-team", "world-car": "land-team" },
    },
  },
  {
    id: "cn-seed-story-m2",
    domain: "chinese", kind: "sequence_3", skillId: "cn.story.sequence", difficulty: 2, ageBand: "36-42m", variantCount: 3,
    title: "一颗种子的故事", skill: "复述三个情节", instruction: "种子怎样变成小花？",
    spokenInstruction: "先把种子放进泥土，再让太阳和雨水来帮忙，最后小花开出来。排一排种子的故事。",
    speechLang: "zh-CN",
    choices: [
      { id: "seed-start", label: "种进土里", icon: "stone", color: "cream" }, { id: "seed-grow", label: "晒太阳喝雨水", icon: "sun", color: "yellow" }, { id: "seed-flower", label: "开出小花", icon: "flower", color: "green" },
    ],
    answerId: "seed-start", hint: "种子要先住进土里，得到阳光雨水后才开花。", successText: "种子的故事被你讲完整了！", parentTip: "照顾植物时用“先、然后、最后”复述变化。", interests: ["nature"],
    interaction: {
      targets: [{ id: "seed-one", label: "开始", color: "cream" }, { id: "seed-two", label: "长大", color: "yellow" }, { id: "seed-three", label: "最后", color: "green" }],
      correctTargets: { "seed-start": "seed-one", "seed-grow": "seed-two", "seed-flower": "seed-three" },
    },
  },
  {
    id: "cn-nature-sound-m2",
    domain: "chinese", kind: "listen_choose", skillId: "cn.listen.sound-detail", difficulty: 1, ageBand: "30-36m", variantCount: 3,
    title: "大自然声音盒", skill: "听辨拟声词", instruction: "“哗啦哗啦”是谁的声音？",
    spokenInstruction: "闭上小耳朵想一想。哗啦，哗啦，一大片水在摇晃。这是谁的声音？",
    speechLang: "zh-CN",
    choices: [
      { id: "sound-water", label: "水浪", icon: "waves", color: "blue" }, { id: "sound-bird", label: "小鸟", icon: "bird", color: "yellow" }, { id: "sound-car", label: "汽车", icon: "car", color: "coral" },
    ],
    answerId: "sound-water", hint: "水摇起来会发出哗啦哗啦的声音。", successText: "哗啦哗啦，水浪被你听出来啦！", parentTip: "一起收集“滴答、沙沙、轰隆”等生活声音。", interests: ["nature", "animals"],
  },
  {
    id: "cn-describe-dino-m2",
    domain: "chinese", kind: "look_choose", skillId: "cn.speak.adjective", difficulty: 1, ageBand: "30-36m", variantCount: 3,
    title: "给恐龙加个形容词", skill: "理解描述性词语", instruction: "哪只恐龙是“大大的”？",
    spokenInstruction: "这里有一只大大的恐龙，也有一只小小的恐龙。请找到大大的那一只。",
    speechLang: "zh-CN",
    choices: [
      { id: "dino-large", label: "大大的", icon: "dinosaur", color: "green", visualScale: "large" }, { id: "dino-small", label: "小小的", icon: "dinosaur", color: "yellow", visualScale: "small" }, { id: "dino-sleep", label: "睡着的", icon: "sleep", color: "purple" },
    ],
    answerId: "dino-large", hint: "大大的恐龙会占更多地方。", successText: "你会用“大大的”来描述恐龙啦！", parentTip: "每天选一个物品，加上颜色、大小或长短来描述。", interests: ["dinosaurs"],
  },
  {
    id: "cn-polite-thanks-m2",
    domain: "chinese", kind: "story_choice", skillId: "cn.dialogue.social", difficulty: 1, ageBand: "30-36m", variantCount: 3,
    title: "收到帮助怎么说", skill: "使用礼貌表达", instruction: "小狗帮忙捡回皮球，我们说什么？",
    spokenInstruction: "皮球滚远了，小狗跑过去帮豆豆龙捡回来。豆豆龙应该对小狗说什么？",
    speechLang: "zh-CN",
    choices: [
      { id: "say-thanks", label: "谢谢你", icon: "thanks", color: "green" }, { id: "say-bye", label: "再见", icon: "bye", color: "blue" }, { id: "say-angry", label: "我生气了", icon: "angry", color: "coral" },
    ],
    answerId: "say-thanks", hint: "别人帮助我们时，可以真诚地说谢谢。", successText: "一句谢谢，让帮助变得暖暖的！", parentTip: "家人互相帮助后也认真说“谢谢”。", interests: ["animals", "dinosaurs"],
    interaction: { storyText: ["豆豆龙的皮球滚远了。", "小狗飞快地追过去。", "它把皮球捡了回来。"] },
  },
  {
    id: "cn-object-use-match-m2",
    domain: "chinese", kind: "drag_match", skillId: "cn.vocabulary.function", difficulty: 2, ageBand: "36-42m", variantCount: 3,
    title: "东西都有什么用", skill: "理解物品功能", instruction: "把物品送到需要它的地方",
    spokenInstruction: "牙刷用来刷牙，雨伞用来挡雨，锤子用来修东西。把它们送到正确的地方。",
    speechLang: "zh-CN",
    choices: [
      { id: "use-brush", label: "牙刷", icon: "toothbrush", color: "blue" }, { id: "use-umbrella", label: "雨伞", icon: "umbrella", color: "purple" }, { id: "use-hammer", label: "锤子", icon: "hammer", color: "yellow" },
    ],
    answerId: "use-brush", hint: "想想什么时候会拿起牙刷、雨伞和锤子。", successText: "每样东西都去做自己擅长的事啦！", parentTip: "拿起日用品时问“它是做什么用的”。", interests: ["construction", "nature"],
    interaction: {
      targets: [{ id: "use-teeth", label: "刷牙", icon: "happy", color: "blue" }, { id: "use-rain", label: "下雨天", icon: "cloud", color: "purple" }, { id: "use-fix", label: "修理", icon: "wrench", color: "yellow" }],
      correctTargets: { "use-brush": "use-teeth", "use-umbrella": "use-rain", "use-hammer": "use-fix" },
    },
  },
  {
    id: "cn-bedtime-sequence-m2",
    domain: "chinese", kind: "sequence_3", skillId: "cn.story.daily-sequence", difficulty: 1, ageBand: "30-36m", variantCount: 3,
    title: "豆豆龙准备睡觉", skill: "讲述生活流程", instruction: "把睡前的三件事排好",
    spokenInstruction: "晚上到了，先刷牙，再看一本小书，最后钻进小床睡觉。帮豆豆龙排好顺序。",
    speechLang: "zh-CN",
    choices: [
      { id: "bed-brush", label: "刷牙", icon: "toothbrush", color: "blue" }, { id: "bed-book", label: "看小书", icon: "book", color: "green" }, { id: "bed-sleep", label: "睡觉", icon: "bed", color: "purple" },
    ],
    answerId: "bed-brush", hint: "先把牙齿刷干净，然后看书，最后睡觉。", successText: "睡前流程排好了，晚安豆豆龙！", parentTip: "每天用相同语言预告睡前步骤，增加安全感。", interests: ["dinosaurs", "animals"],
    interaction: {
      targets: [{ id: "bed-one", label: "先", color: "blue" }, { id: "bed-two", label: "再", color: "green" }, { id: "bed-three", label: "最后", color: "purple" }],
      correctTargets: { "bed-brush": "bed-one", "bed-book": "bed-two", "bed-sleep": "bed-three" },
    },
  },
  {
    id: "cn-not-animal-m2",
    domain: "chinese", kind: "look_choose", skillId: "cn.vocabulary.category-exclusion", difficulty: 1, ageBand: "30-36m", variantCount: 3,
    title: "谁不是小动物", skill: "发现类别例外", instruction: "三个伙伴里，谁不是动物？",
    spokenInstruction: "小鸟、小鱼和小汽车站在一起。仔细看看，哪一个不是会长大的动物？",
    speechLang: "zh-CN",
    choices: [
      { id: "not-bird", label: "小鸟", icon: "bird", color: "yellow" }, { id: "not-fish", label: "小鱼", icon: "fish", color: "blue" }, { id: "not-car", label: "小汽车", icon: "car", color: "coral" },
    ],
    answerId: "not-car", hint: "动物会吃东西、会长大；汽车需要加油或充电。", successText: "找到了，小汽车不是动物！", parentTip: "玩“谁不一样”时请孩子说出理由，不只猜答案。", interests: ["animals", "vehicles"],
  },

  // 数学：5 以内数量、一一对应、比较、形状空间、模式与关系
  {
    id: "math-count-five-stars-m2",
    domain: "math", kind: "tap_count", skillId: "math.number.count5", difficulty: 2, ageBand: "36-42m", variantCount: 3,
    title: "点亮五颗星", skill: "手口一致点数 1–5", instruction: "一颗一颗点亮星星",
    spokenInstruction: "宇宙有五颗小星星在等你。伸出小手，点一颗数一个，一直数到五。",
    speechLang: "zh-CN",
    choices: [
      { id: "star-1", label: "星星", icon: "star", color: "yellow" }, { id: "star-2", label: "星星", icon: "star", color: "blue" }, { id: "star-3", label: "星星", icon: "star", color: "coral" }, { id: "star-4", label: "星星", icon: "star", color: "green" }, { id: "star-5", label: "星星", icon: "star", color: "purple" },
    ],
    answerId: "star-1", hint: "每点一颗就说下一个数字，不要漏掉。", successText: "一、二、三、四、五，五颗星全亮啦！", parentTip: "3～4 岁以手口一致点数 5 个以内物体为主。", interests: ["space"], interaction: { countGoal: 5 },
  },
  {
    id: "math-count-four-wheels-m2",
    domain: "math", kind: "tap_count", skillId: "math.number.count4", difficulty: 1, ageBand: "30-36m", variantCount: 3,
    title: "赛车需要四个轮子", skill: "按数点取 4 个", instruction: "点亮四个轮子",
    spokenInstruction: "小赛车还没有轮子。请你一边点一边数，帮它准备四个圆圆的轮子。",
    speechLang: "zh-CN",
    choices: [
      { id: "wheel-1", label: "轮子", icon: "circle", color: "blue" }, { id: "wheel-2", label: "轮子", icon: "circle", color: "green" }, { id: "wheel-3", label: "轮子", icon: "circle", color: "yellow" }, { id: "wheel-4", label: "轮子", icon: "circle", color: "coral" },
    ],
    answerId: "wheel-1", hint: "慢慢点：一、二、三、四。", successText: "四个轮子装好，赛车出发！", parentTip: "请孩子按要求拿 4 块积木或 4 辆小车。", interests: ["vehicles"], interaction: { countGoal: 4 },
  },
  {
    id: "math-count-three-tools-m2",
    domain: "math", kind: "tap_count", skillId: "math.number.count3", difficulty: 1, ageBand: "30-36m", variantCount: 3,
    title: "工程箱装三件工具", skill: "按数取物 3 个", instruction: "选三件工具装进工程箱",
    spokenInstruction: "工程队要带三件工具出发。点一个数一个，数到三就完成。",
    speechLang: "zh-CN",
    choices: [
      { id: "tool-1", label: "锤子", icon: "hammer", color: "yellow" }, { id: "tool-2", label: "扳手", icon: "wrench", color: "blue" }, { id: "tool-3", label: "刷子", icon: "paintbrush", color: "green" },
    ],
    answerId: "tool-1", hint: "一个、两个、三个，正好停下来。", successText: "三件工具都装进工程箱啦！", parentTip: "做家务前请孩子帮忙拿指定数量的安全物品。", interests: ["construction"], interaction: { countGoal: 3 },
  },
  {
    id: "math-number-quantity-memory-m2",
    domain: "math", kind: "memory_pairs", skillId: "math.number.symbol-quantity", difficulty: 2, ageBand: "36-42m", variantCount: 3,
    title: "数字和数量翻翻乐", skill: "数字与实物数量配对", instruction: "把数字和一样多的东西配成对",
    spokenInstruction: "数字一和一个苹果是一对，数字二和两颗蛋是一对，数字三和三颗星是一对。翻开卡片找朋友。",
    speechLang: "zh-CN",
    choices: [
      { id: "num-one", label: "1", helper: "一个", icon: "circle", color: "coral" }, { id: "qty-one", label: "一个苹果", icon: "apple", color: "coral" },
      { id: "num-two", label: "2", helper: "两个", icon: "square", color: "blue" }, { id: "qty-two", label: "两颗蛋", icon: "egg", color: "blue" },
      { id: "num-three", label: "3", helper: "三个", icon: "triangle", color: "yellow" }, { id: "qty-three", label: "三颗星", icon: "star", color: "yellow" },
    ],
    answerId: "num-one", hint: "先数实物，再找表示这个数量的数字。", successText: "数字和数量朋友都见面了！", parentTip: "先建立数量经验，不要求机械抄写数字。", interests: ["space", "nature"],
    interaction: { correctTargets: { "num-one": "one", "qty-one": "one", "num-two": "two", "qty-two": "two", "num-three": "three", "qty-three": "three" } },
  },
  {
    id: "math-shape-object-memory-m2",
    domain: "math", kind: "memory_pairs", skillId: "math.geometry.shape-object", difficulty: 1, ageBand: "30-36m", variantCount: 3,
    title: "形状藏在生活里", skill: "形状与物体对应", instruction: "找到形状和生活物品的配对",
    spokenInstruction: "圆形像轮子，方形像盒子，三角形像小山。一次翻两张，找到三对形状朋友。",
    speechLang: "zh-CN",
    choices: [
      { id: "shape-circle", label: "圆形", icon: "circle", color: "blue" }, { id: "object-wheel", label: "轮子", icon: "car", color: "blue" },
      { id: "shape-square", label: "方形", icon: "square", color: "yellow" }, { id: "object-box", label: "盒子", icon: "box", color: "yellow" },
      { id: "shape-triangle", label: "三角形", icon: "triangle", color: "green" }, { id: "object-mountain", label: "小山", icon: "triangle", color: "green" },
    ],
    answerId: "shape-circle", hint: "轮子圆圆的，盒子的面方方的。", successText: "你在生活里找到了三种形状！", parentTip: "散步时找圆形、方形、三角形物体。", interests: ["vehicles", "construction"],
    interaction: { correctTargets: { "shape-circle": "circle", "object-wheel": "circle", "shape-square": "square", "object-box": "square", "shape-triangle": "triangle", "object-mountain": "triangle" } },
  },
  {
    id: "math-more-less-dino-m2",
    domain: "math", kind: "look_choose", skillId: "math.quantity.more-less", difficulty: 1, ageBand: "30-36m", variantCount: 3,
    title: "哪边恐龙蛋更多", skill: "直观比较多少", instruction: "看一看，哪一边更多？",
    spokenInstruction: "左边有两颗恐龙蛋，右边有四颗恐龙蛋。不用着急数很多，看看哪一边更多。",
    speechLang: "zh-CN",
    sceneIcons: ["egg", "egg", "egg", "egg"], sceneLabel: "两颗和四颗",
    choices: [
      { id: "more-two", label: "两颗", icon: "egg", color: "blue", visualScale: "small" }, { id: "more-four", label: "四颗", icon: "egg", color: "yellow", visualScale: "large" }, { id: "more-same", label: "一样多", icon: "circle", color: "cream" },
    ],
    answerId: "more-four", hint: "一颗对一颗排队，哪边还剩下就是更多。", successText: "四颗这一边更多！", parentTip: "用一一对应比较两小堆物品的多少。", interests: ["dinosaurs"],
  },
  {
    id: "math-same-quantity-m2",
    domain: "math", kind: "drag_match", skillId: "math.quantity.one-to-one", difficulty: 2, ageBand: "36-42m", variantCount: 3,
    title: "每只小狗一个球", skill: "一一对应", instruction: "给每只小狗送一个球",
    spokenInstruction: "这里有三只小狗，每只小狗都想要一个皮球。把三个球一一送过去，不能漏掉。",
    speechLang: "zh-CN",
    choices: [
      { id: "ball-a", label: "皮球", icon: "ball", color: "coral" }, { id: "ball-b", label: "皮球", icon: "ball", color: "blue" }, { id: "ball-c", label: "皮球", icon: "ball", color: "yellow" },
    ],
    answerId: "ball-a", hint: "一只小狗配一个球，送过的就不要重复。", successText: "每只小狗都有一个球，正好一样多！", parentTip: "吃饭时给每个人摆一个杯子，体验一一对应。", interests: ["animals"],
    interaction: {
      targets: [{ id: "dog-a", label: "小狗一", icon: "dog", color: "coral" }, { id: "dog-b", label: "小狗二", icon: "dog", color: "blue" }, { id: "dog-c", label: "小狗三", icon: "dog", color: "yellow" }],
      correctTargets: { "ball-a": "dog-a", "ball-b": "dog-b", "ball-c": "dog-c" },
    },
  },
  {
    id: "math-size-garage-match-m2",
    domain: "math", kind: "drag_match", skillId: "math.measure.size", difficulty: 1, ageBand: "30-36m", variantCount: 3,
    title: "大车进大车库", skill: "按大小对应", instruction: "把大车和小车送进合适的车库",
    spokenInstruction: "大大的公交车要进大车库，小小的汽车要进小车库。看清大小，再送进去。",
    speechLang: "zh-CN",
    choices: [
      { id: "garage-bus", label: "大公交车", icon: "bus", color: "yellow", visualScale: "large" }, { id: "garage-car", label: "小汽车", icon: "car", color: "coral", visualScale: "small" },
    ],
    answerId: "garage-bus", hint: "大物体需要更大的空间，小物体住小空间。", successText: "大车小车都停进合适的车库啦！", parentTip: "整理时比较“大盒子装大玩具、小盒子装小玩具”。", interests: ["vehicles"],
    interaction: {
      targets: [{ id: "garage-large", label: "大车库", icon: "house", color: "yellow" }, { id: "garage-small", label: "小车库", icon: "house", color: "coral" }],
      correctTargets: { "garage-bus": "garage-large", "garage-car": "garage-small" },
    },
  },
  {
    id: "math-color-sort-four-m2",
    domain: "math", kind: "drag_sort", skillId: "math.classify.color", difficulty: 2, ageBand: "36-42m", variantCount: 3,
    title: "四色维修站", skill: "按单一特征分类", instruction: "把物品送到同颜色的维修站",
    spokenInstruction: "红色、蓝色、黄色、绿色各有自己的维修站。只看颜色，把每样东西送回去。",
    speechLang: "zh-CN",
    choices: [
      { id: "cs-red-car", label: "红汽车", icon: "car", color: "coral" }, { id: "cs-red-apple", label: "红苹果", icon: "apple", color: "coral" },
      { id: "cs-blue-fish", label: "蓝小鱼", icon: "fish", color: "blue" }, { id: "cs-blue-ball", label: "蓝皮球", icon: "ball", color: "blue" },
      { id: "cs-yellow-bus", label: "黄公交", icon: "bus", color: "yellow" }, { id: "cs-green-leaf", label: "绿叶子", icon: "leaf", color: "green" },
    ],
    answerId: "cs-red-car", hint: "这次只看颜色，不看它是车、鱼还是食物。", successText: "四种颜色都回到自己的维修站！", parentTip: "换一个规则重分同一组玩具，培养分类灵活性。", interests: ["vehicles", "nature"],
    interaction: {
      targets: [{ id: "color-red", label: "红色", icon: "red", color: "coral" }, { id: "color-blue", label: "蓝色", icon: "blue", color: "blue" }, { id: "color-yellow", label: "黄色", icon: "yellow", color: "yellow" }, { id: "color-green", label: "绿色", icon: "green", color: "green" }],
      correctTargets: { "cs-red-car": "color-red", "cs-red-apple": "color-red", "cs-blue-fish": "color-blue", "cs-blue-ball": "color-blue", "cs-yellow-bus": "color-yellow", "cs-green-leaf": "color-green" },
    },
  },
  {
    id: "math-shape-sort-m2",
    domain: "math", kind: "drag_sort", skillId: "math.classify.shape", difficulty: 1, ageBand: "30-36m", variantCount: 3,
    title: "形状积木回家", skill: "按形状分类", instruction: "圆形、方形、三角形各自回家",
    spokenInstruction: "圆圆的积木去圆形屋，方方的积木去方形屋，尖尖的三角形去三角屋。",
    speechLang: "zh-CN",
    choices: [
      { id: "ss-circle-a", label: "圆形", icon: "circle", color: "blue" }, { id: "ss-circle-b", label: "圆轮子", icon: "circle", color: "coral" }, { id: "ss-square-a", label: "方形", icon: "square", color: "yellow" }, { id: "ss-square-b", label: "方盒子", icon: "box", color: "cream" }, { id: "ss-triangle-a", label: "三角形", icon: "triangle", color: "green" }, { id: "ss-triangle-b", label: "尖屋顶", icon: "triangle", color: "purple" },
    ],
    answerId: "ss-circle-a", hint: "摸摸想象中的边：圆形没有角，方形四个角，三角形三个角。", successText: "形状积木都找到家啦！", parentTip: "不要只认图卡，也在真实物体上寻找形状。", interests: ["construction"],
    interaction: {
      targets: [{ id: "shape-circle-home", label: "圆形屋", icon: "circle", color: "blue" }, { id: "shape-square-home", label: "方形屋", icon: "square", color: "yellow" }, { id: "shape-triangle-home", label: "三角屋", icon: "triangle", color: "green" }],
      correctTargets: { "ss-circle-a": "shape-circle-home", "ss-circle-b": "shape-circle-home", "ss-square-a": "shape-square-home", "ss-square-b": "shape-square-home", "ss-triangle-a": "shape-triangle-home", "ss-triangle-b": "shape-triangle-home" },
    },
  },
  {
    id: "math-pattern-aab-m2",
    domain: "math", kind: "pattern_extend", skillId: "math.pattern.aab", difficulty: 2, ageBand: "36-42m", variantCount: 3,
    title: "火箭灯光规律", skill: "发现 AAB 规律", instruction: "红、红、蓝，接下来是什么？",
    spokenInstruction: "火箭灯一闪一闪：红、红、蓝，红、红、蓝。最后还缺一盏什么颜色的灯？",
    speechLang: "zh-CN",
    sceneIcons: ["red", "red", "blue", "red", "red"], sceneLabel: "红、红、蓝、红、红、？",
    choices: [
      { id: "aab-blue", label: "蓝色", icon: "blue", color: "blue" }, { id: "aab-red", label: "红色", icon: "red", color: "coral" }, { id: "aab-yellow", label: "黄色", icon: "yellow", color: "yellow" },
    ],
    answerId: "aab-blue", hint: "每一组都是两个红色，再跟一个蓝色。", successText: "红、红、蓝，规律继续下去啦！", parentTip: "用积木摆简单重复规律，让孩子接下一个。", interests: ["space"],
    interaction: { targets: [{ id: "aab-gap", label: "缺少的灯", color: "blue" }], correctTargets: { "aab-blue": "aab-gap" } },
  },
  {
    id: "math-pattern-size-m2",
    domain: "math", kind: "pattern_extend", skillId: "math.pattern.ab-size", difficulty: 1, ageBand: "30-36m", variantCount: 3,
    title: "恐龙脚印大小规律", skill: "发现大小交替", instruction: "大、小、大、小，接下来呢？",
    spokenInstruction: "恐龙留下脚印：大、小、大、小。下一个脚印应该是大大的，还是小小的？",
    speechLang: "zh-CN",
    sceneIcons: ["foot", "foot", "foot", "foot"], sceneLabel: "大、小、大、小、？",
    choices: [
      { id: "size-big-next", label: "大脚印", icon: "foot", color: "green", visualScale: "large" }, { id: "size-small-next", label: "小脚印", icon: "foot", color: "yellow", visualScale: "small" }, { id: "size-star-next", label: "星星", icon: "star", color: "blue" },
    ],
    answerId: "size-big-next", hint: "大小轮流出现，小的后面轮到大的。", successText: "大、小、大、小、大，脚印继续啦！", parentTip: "用大勺小勺交替排队，再请孩子续接。", interests: ["dinosaurs"],
    interaction: { targets: [{ id: "size-gap", label: "下一个脚印", color: "green" }], correctTargets: { "size-big-next": "size-gap" } },
  },
  {
    id: "math-spatial-rocket-m2",
    domain: "math", kind: "place_in_scene", skillId: "math.spatial.up-down", difficulty: 1, ageBand: "30-36m", variantCount: 3,
    title: "火箭飞到星星上方", skill: "理解上面和下面", instruction: "把火箭放到星星上面",
    spokenInstruction: "星星在这里。请把火箭放到星星的上面，再把小汽车留在星星的下面。",
    speechLang: "zh-CN",
    choices: [
      { id: "spatial-rocket", label: "火箭", icon: "rocket", color: "coral" }, { id: "spatial-car", label: "小汽车", icon: "car", color: "blue" },
    ],
    answerId: "spatial-rocket", hint: "上面靠近天空，下面靠近地面。", successText: "火箭在上面，汽车在下面！", parentTip: "在家玩“玩具放桌上、放桌下”的位置指令。", interests: ["space", "vehicles"],
    interaction: {
      targets: [{ id: "space-above", label: "星星上面", icon: "star", color: "yellow" }, { id: "space-below", label: "星星下面", icon: "star", color: "blue" }],
      correctTargets: { "spatial-rocket": "space-above", "spatial-car": "space-below" },
    },
  },
  {
    id: "math-order-small-large-m2",
    domain: "math", kind: "sequence_3", skillId: "math.measure.order-size", difficulty: 2, ageBand: "36-42m", variantCount: 3,
    title: "恐龙从小到大排队", skill: "按大小排序", instruction: "小、中、大，排成一队",
    spokenInstruction: "三只恐龙要从小到大排队。最小的站前面，中等的站中间，最大的站最后。",
    speechLang: "zh-CN",
    choices: [
      { id: "dino-small-order", label: "小恐龙", icon: "dinosaur", color: "yellow", visualScale: "small" }, { id: "dino-medium-order", label: "中恐龙", icon: "dinosaur", color: "blue", visualScale: "medium" }, { id: "dino-large-order", label: "大恐龙", icon: "dinosaur", color: "green", visualScale: "large" },
    ],
    answerId: "dino-small-order", hint: "先找最小的，再找最大的，中等的放中间。", successText: "小、中、大，恐龙队伍排好啦！", parentTip: "用三件明显不同大小的物品练习排序。", interests: ["dinosaurs"],
    interaction: {
      targets: [{ id: "size-first", label: "最小", color: "yellow" }, { id: "size-second", label: "中等", color: "blue" }, { id: "size-third", label: "最大", color: "green" }],
      correctTargets: { "dino-small-order": "size-first", "dino-medium-order": "size-second", "dino-large-order": "size-third" },
    },
  },
  {
    id: "math-which-fits-m2",
    domain: "math", kind: "look_choose", skillId: "math.spatial.fit", difficulty: 1, ageBand: "30-36m", variantCount: 3,
    title: "哪个积木能滚下去", skill: "感知形状特征", instruction: "哪个形状最容易滚动？",
    spokenInstruction: "斜坡准备好了。圆形没有尖角，会咕噜咕噜滚下去。请找到最容易滚的形状。",
    speechLang: "zh-CN",
    choices: [
      { id: "roll-circle", label: "圆形", icon: "circle", color: "blue" }, { id: "roll-square", label: "方形", icon: "square", color: "yellow" }, { id: "roll-triangle", label: "三角形", icon: "triangle", color: "green" },
    ],
    answerId: "roll-circle", hint: "圆形的边弯弯的，没有角挡住。", successText: "圆形咕噜咕噜滚下坡！", parentTip: "让安全物品在缓坡上滚一滚，先猜再验证。", interests: ["construction", "vehicles"],
  },

  // 英语：以听说、动作、歌曲式节奏和生活词汇为主，不做超龄拼写训练
  {
    id: "en-touch-your-nose-m2",
    domain: "english", kind: "listen_choose", skillId: "en.tpr.body", difficulty: 1, ageBand: "30-36m", variantCount: 3,
    title: "Touch your nose", skill: "听懂身体动作指令", instruction: "听一听，应该摸哪里？",
    spokenInstruction: "Touch your nose. Nose, nose, touch your nose!",
    speechLang: "en-US",
    choices: [
      { id: "touch-nose", label: "Nose", helper: "鼻子", icon: "nose", color: "coral" }, { id: "touch-hand", label: "Hand", helper: "手", icon: "hand", color: "yellow" }, { id: "touch-foot", label: "Foot", helper: "脚", icon: "foot", color: "blue" },
    ],
    answerId: "touch-nose", hint: "Nose 是鼻子，和家长一起指指鼻子。", successText: "Touch your nose! 你听懂动作啦！", parentTip: "英语先通过动作建立意义，不急着要求跟读。", interests: ["animals", "dinosaurs"],
  },
  {
    id: "en-jump-run-sleep-m2",
    domain: "english", kind: "listen_choose", skillId: "en.tpr.actions", difficulty: 1, ageBand: "30-36m", variantCount: 3,
    title: "Jump like a dinosaur", skill: "听辨动作词", instruction: "豆豆龙说了哪个动作？",
    spokenInstruction: "Jump, jump, jump like a dinosaur! Which one means jump?",
    speechLang: "en-US",
    choices: [
      { id: "action-jump", label: "Jump", helper: "跳一跳", icon: "jump", color: "green" }, { id: "action-run", label: "Run", helper: "跑一跑", icon: "run", color: "coral" }, { id: "action-sleep", label: "Sleep", helper: "睡觉", icon: "sleep", color: "purple" },
    ],
    answerId: "action-jump", hint: "Jump 就是双脚轻轻跳起来。", successText: "Jump! 小恐龙跳起来啦！", parentTip: "用 jump、run、stop 玩一分钟动作游戏。", interests: ["dinosaurs"],
  },
  {
    id: "en-body-memory-m2",
    domain: "english", kind: "memory_pairs", skillId: "en.vocabulary.body", difficulty: 1, ageBand: "30-36m", variantCount: 3,
    title: "Body words 翻翻乐", skill: "身体词汇中英对应", instruction: "把英文身体词和图片配成对",
    spokenInstruction: "Nose is 鼻子. Hand is 手. Foot is 脚. Flip two cards and find the pairs!",
    speechLang: "en-US",
    choices: [
      { id: "body-nose-word", label: "Nose", icon: "nose", color: "coral" }, { id: "body-nose-cn", label: "鼻子", icon: "nose", color: "coral" },
      { id: "body-hand-word", label: "Hand", icon: "hand", color: "yellow" }, { id: "body-hand-cn", label: "小手", icon: "hand", color: "yellow" },
      { id: "body-foot-word", label: "Foot", icon: "foot", color: "blue" }, { id: "body-foot-cn", label: "小脚", icon: "foot", color: "blue" },
    ],
    answerId: "body-nose-word", hint: "看图也可以摸摸自己，Nose、Hand、Foot。", successText: "Three body-word pairs! 三对都找到啦！", parentTip: "洗澡或穿衣时自然重复身体部位英文。", interests: ["animals"],
    interaction: { correctTargets: { "body-nose-word": "nose", "body-nose-cn": "nose", "body-hand-word": "hand", "body-hand-cn": "hand", "body-foot-word": "foot", "body-foot-cn": "foot" } },
  },
  {
    id: "en-color-memory-m2",
    domain: "english", kind: "memory_pairs", skillId: "en.vocabulary.colors", difficulty: 1, ageBand: "30-36m", variantCount: 3,
    title: "Color pairs 翻翻乐", skill: "颜色词与颜色对应", instruction: "找到英文颜色和它的颜色卡",
    spokenInstruction: "Red is 红色. Blue is 蓝色. Yellow is 黄色. Flip two cards and find the color pairs!",
    speechLang: "en-US",
    choices: [
      { id: "color-red-word", label: "Red", icon: "red", color: "coral" }, { id: "color-red-card", label: "红色", icon: "apple", color: "coral" },
      { id: "color-blue-word", label: "Blue", icon: "blue", color: "blue" }, { id: "color-blue-card", label: "蓝色", icon: "fish", color: "blue" },
      { id: "color-yellow-word", label: "Yellow", icon: "yellow", color: "yellow" }, { id: "color-yellow-card", label: "黄色", icon: "banana", color: "yellow" },
    ],
    answerId: "color-red-word", hint: "苹果提示 Red，小鱼提示 Blue，香蕉提示 Yellow。", successText: "Red, blue, yellow! 颜色朋友到齐了！", parentTip: "每天只在真实物品上复习两三个颜色词。", interests: ["nature", "animals"],
    interaction: { correctTargets: { "color-red-word": "red", "color-red-card": "red", "color-blue-word": "blue", "color-blue-card": "blue", "color-yellow-word": "yellow", "color-yellow-card": "yellow" } },
  },
  {
    id: "en-animal-sounds-m2",
    domain: "english", kind: "story_choice", skillId: "en.listen.animals", difficulty: 1, ageBand: "30-36m", variantCount: 3,
    title: "Who says woof?", skill: "听辨动物词", instruction: "“Woof, woof” 是谁？",
    spokenInstruction: "Woof, woof! I have four legs and a wagging tail. Who am I?",
    speechLang: "en-US",
    choices: [
      { id: "sound-dog-en", label: "Dog", helper: "小狗", icon: "dog", color: "coral" }, { id: "sound-cat-en", label: "Cat", helper: "小猫", icon: "cat", color: "yellow" }, { id: "sound-bird-en", label: "Bird", helper: "小鸟", icon: "bird", color: "blue" },
    ],
    answerId: "sound-dog-en", hint: "Dog 是小狗，会 woof woof 地叫。", successText: "Woof, woof! It is a dog!", parentTip: "用动物声音做线索，让孩子猜英文动物词。", interests: ["animals"],
    interaction: { storyText: ["Woof, woof!", "I have four legs.", "My tail can wag."] },
  },
  {
    id: "en-rainy-weather-m2",
    domain: "english", kind: "story_choice", skillId: "en.vocabulary.weather", difficulty: 1, ageBand: "30-36m", variantCount: 3,
    title: "It is rainy", skill: "理解天气词", instruction: "天空在下雨，天气怎么说？",
    spokenInstruction: "Drip, drop, drip, drop. It is rainy today. Which picture means rainy?",
    speechLang: "en-US",
    choices: [
      { id: "weather-rainy", label: "Rainy", helper: "下雨的", icon: "cloud", color: "blue" }, { id: "weather-sunny", label: "Sunny", helper: "晴朗的", icon: "sun", color: "yellow" }, { id: "weather-sleepy", label: "Sleepy", helper: "困困的", icon: "sleep", color: "purple" },
    ],
    answerId: "weather-rainy", hint: "Rain 是雨，rainy 就是下雨的天气。", successText: "It is rainy! 记得带 umbrella！", parentTip: "每天出门前用 sunny 或 rainy 描述一次天气。", interests: ["nature"],
    interaction: { storyText: ["Clouds cover the sky.", "Drip, drop, drip, drop.", "Take an umbrella!"] },
  },
  {
    id: "en-food-please-m2",
    domain: "english", kind: "story_choice", skillId: "en.dialogue.request", difficulty: 1, ageBand: "30-36m", variantCount: 3,
    title: "An apple, please", skill: "理解简单请求", instruction: "豆豆龙想要苹果，应该选哪句？",
    spokenInstruction: "Doudou Dragon is hungry. He wants an apple. He says: An apple, please!",
    speechLang: "en-US",
    choices: [
      { id: "food-apple-en", label: "Apple", helper: "苹果", icon: "apple", color: "coral" }, { id: "food-banana-en", label: "Banana", helper: "香蕉", icon: "banana", color: "yellow" }, { id: "food-egg-en", label: "Egg", helper: "鸡蛋", icon: "egg", color: "cream" },
    ],
    answerId: "food-apple-en", hint: "Apple 是苹果，please 让请求听起来更友好。", successText: "An apple, please. Thank you!", parentTip: "点心时间用“Banana, please”做真实沟通。", interests: ["dinosaurs", "nature"],
    interaction: { storyText: ["Doudou is hungry.", "He sees fruit on the table.", "He wants an apple."] },
  },
  {
    id: "en-vehicle-word-match-m2",
    domain: "english", kind: "drag_match", skillId: "en.vocabulary.vehicles", difficulty: 2, ageBand: "36-42m", variantCount: 3,
    title: "Vehicle word garage", skill: "交通工具词图配对", instruction: "把英文词送给对应的交通工具",
    spokenInstruction: "Car is 小汽车. Bus is 公交车. Train is 火车. Match each English word to the right vehicle.",
    speechLang: "en-US",
    choices: [
      { id: "vehicle-car-word", label: "Car", icon: "car", color: "coral" }, { id: "vehicle-bus-word", label: "Bus", icon: "bus", color: "yellow" }, { id: "vehicle-train-word", label: "Train", icon: "train", color: "green" },
    ],
    answerId: "vehicle-car-word", hint: "Car、Bus、Train，先听声音再看图片。", successText: "Car, bus, train—all matched!", parentTip: "在路上看到真实车辆时说一次英文即可。", interests: ["vehicles"],
    interaction: {
      targets: [{ id: "vehicle-car-picture", label: "小汽车", icon: "car", color: "coral" }, { id: "vehicle-bus-picture", label: "公交车", icon: "bus", color: "yellow" }, { id: "vehicle-train-picture", label: "火车", icon: "train", color: "green" }],
      correctTargets: { "vehicle-car-word": "vehicle-car-picture", "vehicle-bus-word": "vehicle-bus-picture", "vehicle-train-word": "vehicle-train-picture" },
    },
  },
  {
    id: "en-animal-word-match-m2",
    domain: "english", kind: "drag_match", skillId: "en.vocabulary.animals", difficulty: 2, ageBand: "36-42m", variantCount: 3,
    title: "Animal word forest", skill: "动物词图配对", instruction: "把英文词送给对应的小动物",
    spokenInstruction: "Cat is 小猫. Dog is 小狗. Bird is 小鸟. Match each word to its animal friend.",
    speechLang: "en-US",
    choices: [
      { id: "animal-cat-word", label: "Cat", icon: "cat", color: "yellow" }, { id: "animal-dog-word", label: "Dog", icon: "dog", color: "coral" }, { id: "animal-bird-word", label: "Bird", icon: "bird", color: "blue" },
    ],
    answerId: "animal-cat-word", hint: "Cat 喵喵，Dog 汪汪，Bird 啾啾。", successText: "Cat, dog, bird—all home!", parentTip: "词图配对后让孩子任选一个做动作或叫声。", interests: ["animals", "nature"],
    interaction: {
      targets: [{ id: "animal-cat-picture", label: "小猫", icon: "cat", color: "yellow" }, { id: "animal-dog-picture", label: "小狗", icon: "dog", color: "coral" }, { id: "animal-bird-picture", label: "小鸟", icon: "bird", color: "blue" }],
      correctTargets: { "animal-cat-word": "animal-cat-picture", "animal-dog-word": "animal-dog-picture", "animal-bird-word": "animal-bird-picture" },
    },
  },
  {
    id: "en-animal-vehicle-sort-m2",
    domain: "english", kind: "drag_sort", skillId: "en.vocabulary.categories", difficulty: 2, ageBand: "36-42m", variantCount: 3,
    title: "Animals and vehicles", skill: "英文类别理解", instruction: "把 animals 和 vehicles 分开",
    spokenInstruction: "Cat, dog and bird are animals. Car, bus and train are vehicles. Sort them into two teams.",
    speechLang: "en-US",
    choices: [
      { id: "av-cat", label: "Cat", icon: "cat", color: "yellow" }, { id: "av-dog", label: "Dog", icon: "dog", color: "coral" }, { id: "av-bird", label: "Bird", icon: "bird", color: "blue" },
      { id: "av-car", label: "Car", icon: "car", color: "coral" }, { id: "av-bus", label: "Bus", icon: "bus", color: "yellow" }, { id: "av-train", label: "Train", icon: "train", color: "green" },
    ],
    answerId: "av-cat", hint: "Animals 会吃东西和长大，vehicles 带我们出发。", successText: "Animals here, vehicles there—great sorting!", parentTip: "分类任务同时练词义，不要求孩子拼写。", interests: ["animals", "vehicles"],
    interaction: {
      targets: [{ id: "animals-team-en", label: "Animals", icon: "dog", color: "green" }, { id: "vehicles-team-en", label: "Vehicles", icon: "car", color: "yellow" }],
      correctTargets: { "av-cat": "animals-team-en", "av-dog": "animals-team-en", "av-bird": "animals-team-en", "av-car": "vehicles-team-en", "av-bus": "vehicles-team-en", "av-train": "vehicles-team-en" },
    },
  },
  {
    id: "en-color-sort-m2",
    domain: "english", kind: "drag_sort", skillId: "en.vocabulary.color-sort", difficulty: 2, ageBand: "36-42m", variantCount: 3,
    title: "Red, blue, green", skill: "按英文颜色指令分类", instruction: "把物品送到英文颜色站",
    spokenInstruction: "Red, blue and green. Put each thing into the matching color station.",
    speechLang: "en-US",
    choices: [
      { id: "ecs-apple", label: "Apple", icon: "apple", color: "coral" }, { id: "ecs-car", label: "Car", icon: "car", color: "coral" }, { id: "ecs-fish", label: "Fish", icon: "fish", color: "blue" }, { id: "ecs-ball", label: "Ball", icon: "ball", color: "blue" }, { id: "ecs-leaf", label: "Leaf", icon: "leaf", color: "green" }, { id: "ecs-tree", label: "Tree", icon: "tree", color: "green" },
    ],
    answerId: "ecs-apple", hint: "Red 是红色，Blue 是蓝色，Green 是绿色。", successText: "Red, blue, green—everything is sorted!", parentTip: "先听英文颜色，再根据视觉分类，降低语言负担。", interests: ["nature", "vehicles"],
    interaction: {
      targets: [{ id: "ecs-red", label: "Red", icon: "red", color: "coral" }, { id: "ecs-blue", label: "Blue", icon: "blue", color: "blue" }, { id: "ecs-green", label: "Green", icon: "green", color: "green" }],
      correctTargets: { "ecs-apple": "ecs-red", "ecs-car": "ecs-red", "ecs-fish": "ecs-blue", "ecs-ball": "ecs-blue", "ecs-leaf": "ecs-green", "ecs-tree": "ecs-green" },
    },
  },
  {
    id: "en-in-on-under-m2",
    domain: "english", kind: "place_in_scene", skillId: "en.vocabulary.position", difficulty: 2, ageBand: "36-42m", variantCount: 3,
    title: "In and under", skill: "理解位置词", instruction: "把球放进盒子，把狗放到树下",
    spokenInstruction: "Put the ball in the box. Put the dog under the tree. In the box, under the tree.",
    speechLang: "en-US",
    choices: [
      { id: "position-ball", label: "Ball", icon: "ball", color: "coral" }, { id: "position-dog", label: "Dog", icon: "dog", color: "yellow" },
    ],
    answerId: "position-ball", hint: "In 是里面，under 是下面。", successText: "Ball in the box, dog under the tree!", parentTip: "拿真实玩具玩 in、on、under，比背词更有效。", interests: ["animals", "nature"],
    interaction: {
      targets: [{ id: "position-box", label: "In the box", icon: "box", color: "coral" }, { id: "position-tree", label: "Under the tree", icon: "tree", color: "green" }],
      correctTargets: { "position-ball": "position-box", "position-dog": "position-tree" },
    },
  },
  {
    id: "en-morning-sequence-m2",
    domain: "english", kind: "sequence_3", skillId: "en.vocabulary.routine", difficulty: 2, ageBand: "36-42m", variantCount: 3,
    title: "Good morning routine", skill: "在情境中理解日常短语", instruction: "把早晨的英语动作排好",
    spokenInstruction: "Wake up, brush your teeth, put on your shoes. First wake up, then brush, then shoes.",
    speechLang: "en-US",
    choices: [
      { id: "morning-wake-en", label: "Wake up", icon: "bed", color: "purple" }, { id: "morning-brush-en", label: "Brush", icon: "toothbrush", color: "blue" }, { id: "morning-shoes-en", label: "Shoes", icon: "shoe", color: "yellow" },
    ],
    answerId: "morning-wake-en", hint: "先 Wake up，再 Brush，最后穿 Shoes。", successText: "Wake up, brush, shoes—good morning!", parentTip: "把英语短语嵌入每天真实、固定的生活流程。", interests: ["animals"],
    interaction: {
      targets: [{ id: "morning-one-en", label: "First", color: "purple" }, { id: "morning-two-en", label: "Then", color: "blue" }, { id: "morning-three-en", label: "Last", color: "yellow" }],
      correctTargets: { "morning-wake-en": "morning-one-en", "morning-brush-en": "morning-two-en", "morning-shoes-en": "morning-three-en" },
    },
  },
  {
    id: "en-count-three-rockets-m2",
    domain: "english", kind: "tap_count", skillId: "en.number.one-three", difficulty: 1, ageBand: "30-36m", variantCount: 3,
    title: "Three rockets", skill: "英语 1–3 数词", instruction: "点一架，数一个英文数字",
    spokenInstruction: "Let us count the rockets. One, two, three. Tap each rocket and count to three!",
    speechLang: "en-US",
    choices: [
      { id: "rocket-one-en", label: "Rocket", icon: "rocket", color: "coral" }, { id: "rocket-two-en", label: "Rocket", icon: "rocket", color: "blue" }, { id: "rocket-three-en", label: "Rocket", icon: "rocket", color: "yellow" },
    ],
    answerId: "rocket-one-en", hint: "One, two, three，一架一架慢慢点。", successText: "One, two, three—blast off!", parentTip: "用动作和实物练英文数词，不做数字翻译测验。", interests: ["space"], interaction: { countGoal: 3 },
  },
  {
    id: "en-big-small-m2",
    domain: "english", kind: "listen_choose", skillId: "en.vocabulary.size", difficulty: 1, ageBand: "30-36m", variantCount: 3,
    title: "A big dinosaur", skill: "听辨大小形容词", instruction: "听到了 big 还是 small？",
    spokenInstruction: "Look! A big dinosaur. Big, big, big! Find the big dinosaur.",
    speechLang: "en-US",
    choices: [
      { id: "big-dino-en", label: "Big", helper: "大大的", icon: "dinosaur", color: "green", visualScale: "large" }, { id: "small-dino-en", label: "Small", helper: "小小的", icon: "dinosaur", color: "yellow", visualScale: "small" }, { id: "sleep-dino-en", label: "Sleep", helper: "睡觉", icon: "sleep", color: "purple" },
    ],
    answerId: "big-dino-en", hint: "Big 是大大的，small 是小小的。", successText: "A big dinosaur! Roar!", parentTip: "拿两个大小明显不同的玩具说 big 和 small。", interests: ["dinosaurs"],
  },
];
