import type { LearningActivity } from "./learning";

export const M1_ACTIVITY_LIBRARY: LearningActivity[] = [
  // 中文：新增 9 个活动
  {
    id: "cn-builder-command-m1",
    domain: "chinese",
    kind: "listen_choose",
    skillId: "cn.listen.action",
    difficulty: 1,
    ageBand: "30-36m",
    variantCount: 2,
    title: "工程车听指挥",
    skill: "听懂单步指令",
    instruction: "谁来把土挖开？",
    spokenInstruction: "请挖掘机来帮忙，把泥土挖开。谁是挖掘机？",
    speechLang: "zh-CN",
    choices: [
      { id: "excavator", label: "挖掘机", icon: "excavator", color: "yellow" },
      { id: "car", label: "小汽车", icon: "car", color: "coral" },
      { id: "hammer", label: "小锤子", icon: "hammer", color: "blue" },
    ],
    answerId: "excavator",
    hint: "它有一只长长的大铲斗。",
    successText: "轰隆隆，挖掘机来帮忙啦！",
    parentTip: "看到工程车时，说一个动作词：挖、推或装。",
    interests: ["construction", "vehicles"],
  },
  {
    id: "cn-dino-friends-match-m1",
    domain: "chinese",
    kind: "drag_match",
    skillId: "cn.vocabulary.relationships",
    difficulty: 2,
    ageBand: "36-42m",
    variantCount: 2,
    title: "把礼物送给伙伴",
    skill: "理解物品与对象关系",
    instruction: "把礼物送给喜欢它的伙伴",
    spokenInstruction: "绿叶送给小恐龙，苹果送给小兔子，皮球送给小狗。拖一拖，送过去吧。",
    speechLang: "zh-CN",
    choices: [
      { id: "leaf-gift", label: "绿叶", icon: "leaf", color: "green" },
      { id: "apple-gift", label: "苹果", icon: "apple", color: "coral" },
      { id: "ball-gift", label: "皮球", icon: "ball", color: "blue" },
    ],
    answerId: "leaf-gift",
    hint: "听一听：恐龙爱绿叶，小兔爱苹果，小狗爱皮球。",
    successText: "每个伙伴都收到喜欢的礼物啦！",
    parentTip: "收玩具时说“皮球给小狗、树叶给恐龙”。",
    interests: ["dinosaurs", "animals"],
    interaction: {
      targets: [
        { id: "dino-target", label: "小恐龙", icon: "dinosaur", color: "green" },
        { id: "rabbit-target", label: "小兔子", icon: "rabbit", color: "yellow" },
        { id: "dog-target", label: "小狗", icon: "dog", color: "blue" },
      ],
      correctTargets: {
        "leaf-gift": "dino-target",
        "apple-gift": "rabbit-target",
        "ball-gift": "dog-target",
      },
    },
  },
  {
    id: "cn-animal-home-match-m1",
    domain: "chinese",
    kind: "drag_match",
    skillId: "cn.vocabulary.habitat",
    difficulty: 1,
    ageBand: "30-36m",
    variantCount: 2,
    title: "动物回到家",
    skill: "理解动物生活环境",
    instruction: "送动物回到自己的家",
    spokenInstruction: "小鸟住在树上，小鱼住在水里，小狗回到小房子。送它们回家吧。",
    speechLang: "zh-CN",
    choices: [
      { id: "bird-home", label: "小鸟", icon: "bird", color: "yellow" },
      { id: "fish-home", label: "小鱼", icon: "fish", color: "blue" },
      { id: "dog-home", label: "小狗", icon: "dog", color: "coral" },
    ],
    answerId: "bird-home",
    hint: "想一想，谁会飞上树，谁会游进水里？",
    successText: "天黑啦，动物们都安全到家了！",
    parentTip: "散步时聊聊小鸟、小鱼和小狗住在哪里。",
    interests: ["animals", "nature"],
    interaction: {
      targets: [
        { id: "tree-target", label: "树上", icon: "tree", color: "green" },
        { id: "water-target", label: "水里", icon: "waves", color: "blue" },
        { id: "house-target", label: "小屋", icon: "house", color: "yellow" },
      ],
      correctTargets: {
        "bird-home": "tree-target",
        "fish-home": "water-target",
        "dog-home": "house-target",
      },
    },
  },
  {
    id: "cn-vehicle-sound-story-m1",
    domain: "chinese",
    kind: "story_choice",
    skillId: "cn.listen.sound",
    difficulty: 1,
    ageBand: "30-36m",
    variantCount: 2,
    title: "城市声音侦探",
    skill: "声音与物体对应",
    instruction: "“呜——”是谁的声音？",
    spokenInstruction: "清晨，远处传来呜——呜——的声音，还有好多节车厢。是谁来了？",
    speechLang: "zh-CN",
    choices: [
      { id: "train-sound", label: "火车", icon: "train", color: "green" },
      { id: "bus-sound", label: "公交车", icon: "bus", color: "yellow" },
      { id: "ship-sound", label: "轮船", icon: "ship", color: "blue" },
    ],
    answerId: "train-sound",
    hint: "它有一节、两节、好多节车厢。",
    successText: "听出来啦，长长的火车进站了！",
    parentTip: "和孩子轮流模仿一种交通工具的声音。",
    interests: ["vehicles"],
    interaction: {
      storyText: ["清晨，城市刚刚醒来。", "远处传来“呜——呜——”。", "长长的车厢开过来了。"],
    },
  },
  {
    id: "cn-morning-sequence-m1",
    domain: "chinese",
    kind: "sequence_3",
    skillId: "cn.story.sequence",
    difficulty: 2,
    ageBand: "36-42m",
    variantCount: 2,
    title: "早晨三件事",
    skill: "理解生活顺序",
    instruction: "把早晨的事情排好队",
    spokenInstruction: "早上先起床，再刷牙，最后穿好鞋。把三件事排成一排吧。",
    speechLang: "zh-CN",
    choices: [
      { id: "wake-step", label: "起床", icon: "bed", color: "purple" },
      { id: "brush-step", label: "刷牙", icon: "toothbrush", color: "blue" },
      { id: "shoe-step", label: "穿鞋", icon: "shoe", color: "yellow" },
    ],
    answerId: "wake-step",
    hint: "听一听：先起床，再刷牙，最后穿鞋。",
    successText: "起床、刷牙、穿鞋，早晨准备好啦！",
    parentTip: "明早用“先、再、最后”说一遍真实流程。",
    interests: ["animals", "nature"],
    interaction: {
      targets: [
        { id: "step-one", label: "先", helper: "第 1 步", color: "coral" },
        { id: "step-two", label: "再", helper: "第 2 步", color: "yellow" },
        { id: "step-three", label: "最后", helper: "第 3 步", color: "green" },
      ],
      correctTargets: {
        "wake-step": "step-one",
        "brush-step": "step-two",
        "shoe-step": "step-three",
      },
    },
  },
  {
    id: "cn-rain-story-m1",
    domain: "chinese",
    kind: "story_choice",
    skillId: "cn.story.cause",
    difficulty: 1,
    ageBand: "30-36m",
    variantCount: 2,
    title: "下雨以后怎么办",
    skill: "理解简单因果",
    instruction: "下雨了，出门带什么？",
    spokenInstruction: "天空飘来乌云，滴答滴答下雨啦。豆豆龙要出门，它应该带什么？",
    speechLang: "zh-CN",
    choices: [
      { id: "umbrella-rain", label: "雨伞", icon: "umbrella", color: "blue" },
      { id: "banana-rain", label: "香蕉", icon: "banana", color: "yellow" },
      { id: "ball-rain", label: "皮球", icon: "ball", color: "coral" },
    ],
    answerId: "umbrella-rain",
    hint: "雨伞撑开以后，会挡住小雨点。",
    successText: "撑开雨伞，豆豆龙不会淋湿啦！",
    parentTip: "遇到天气变化时，请孩子说说需要准备什么。",
    interests: ["nature", "dinosaurs"],
    interaction: {
      storyText: ["乌云慢慢飘过来。", "滴答、滴答，下雨了。", "豆豆龙准备出门。"],
    },
  },
  {
    id: "cn-rocket-sequence-m1",
    domain: "chinese",
    kind: "sequence_3",
    skillId: "cn.story.sequence",
    difficulty: 2,
    ageBand: "36-42m",
    variantCount: 2,
    title: "火箭发射三步走",
    skill: "理解事件先后",
    instruction: "帮火箭排好发射顺序",
    spokenInstruction: "先把补给装进箱子，再坐进火箭，最后飞向星星。排好顺序吧。",
    speechLang: "zh-CN",
    choices: [
      { id: "pack-step", label: "装补给", icon: "box", color: "yellow" },
      { id: "rocket-step", label: "坐火箭", icon: "rocket", color: "coral" },
      { id: "star-step", label: "到星星", icon: "star", color: "blue" },
    ],
    answerId: "pack-step",
    hint: "先装好东西，再出发，最后才会到星星。",
    successText: "顺序排好，三、二、一，出发！",
    parentTip: "做事前一起说“先做什么，再做什么”。",
    interests: ["space", "construction"],
    interaction: {
      targets: [
        { id: "rocket-one", label: "先", helper: "第 1 步", color: "yellow" },
        { id: "rocket-two", label: "再", helper: "第 2 步", color: "coral" },
        { id: "rocket-three", label: "最后", helper: "第 3 步", color: "blue" },
      ],
      correctTargets: {
        "pack-step": "rocket-one",
        "rocket-step": "rocket-two",
        "star-step": "rocket-three",
      },
    },
  },
  {
    id: "cn-sort-city-things-m1",
    domain: "chinese",
    kind: "drag_sort",
    skillId: "cn.vocabulary.categories",
    difficulty: 2,
    ageBand: "36-42m",
    variantCount: 2,
    title: "城市伙伴分分组",
    skill: "理解类别边界",
    instruction: "把交通工具和动物分开",
    spokenInstruction: "汽车、公交车和火车是交通工具。小狗、小鸟和小鱼是动物。把它们分到两边吧。",
    speechLang: "zh-CN",
    choices: [
      { id: "sort-car", label: "汽车", icon: "car", color: "coral" },
      { id: "sort-bus", label: "公交车", icon: "bus", color: "yellow" },
      { id: "sort-train", label: "火车", icon: "train", color: "green" },
      { id: "sort-dog", label: "小狗", icon: "dog", color: "cream" },
      { id: "sort-bird", label: "小鸟", icon: "bird", color: "blue" },
      { id: "sort-fish", label: "小鱼", icon: "fish", color: "purple" },
    ],
    answerId: "sort-car",
    hint: "能载我们出发的是交通工具，会吃东西长大的是动物。",
    successText: "分好啦，交通工具和动物都找到队伍了！",
    parentTip: "整理玩具时按“车”和“动物”分成两组。",
    interests: ["vehicles", "animals"],
    interaction: {
      targets: [
        { id: "vehicle-bin", label: "交通工具", icon: "car", color: "yellow" },
        { id: "animal-bin", label: "小动物", icon: "dog", color: "green" },
      ],
      correctTargets: {
        "sort-car": "vehicle-bin",
        "sort-bus": "vehicle-bin",
        "sort-train": "vehicle-bin",
        "sort-dog": "animal-bin",
        "sort-bird": "animal-bin",
        "sort-fish": "animal-bin",
      },
    },
  },
  {
    id: "cn-size-words-m1",
    domain: "chinese",
    kind: "look_choose",
    skillId: "cn.vocabulary.adjectives",
    difficulty: 1,
    ageBand: "30-36m",
    variantCount: 2,
    title: "大大的和小小的",
    skill: "理解大小形容词",
    instruction: "哪一只是大大的恐龙？",
    spokenInstruction: "找一找，大大的恐龙在哪里？",
    speechLang: "zh-CN",
    choices: [
      { id: "big-dino", label: "大大的", icon: "dinosaur", color: "green", visualScale: "large" },
      { id: "small-dino", label: "小小的", icon: "dinosaur", color: "yellow", visualScale: "small" },
      { id: "little-egg", label: "恐龙蛋", icon: "egg", color: "blue", visualScale: "medium" },
    ],
    answerId: "big-dino",
    hint: "看看谁占的地方最多、身体最高。",
    successText: "找到大大的恐龙啦！",
    parentTip: "在家找一大一小两个物品，说说“大”和“小”。",
    interests: ["dinosaurs"],
  },

  // 数学：新增 9 个活动
  {
    id: "math-load-three-stones-m1",
    domain: "math",
    kind: "tap_count",
    skillId: "math.cardinality.1-3",
    difficulty: 1,
    ageBand: "30-36m",
    variantCount: 2,
    title: "给卡车装三块石头",
    skill: "1–3 一一对应",
    instruction: "点三块石头装上车",
    spokenInstruction: "卡车需要三块石头。点一块，数一个，一起装三块。",
    speechLang: "zh-CN",
    choices: [
      { id: "stone-1", label: "石头", icon: "stone", color: "cream" },
      { id: "stone-2", label: "石头", icon: "stone", color: "yellow" },
      { id: "stone-3", label: "石头", icon: "stone", color: "cream" },
      { id: "stone-4", label: "石头", icon: "stone", color: "yellow" },
      { id: "stone-5", label: "石头", icon: "stone", color: "cream" },
    ],
    answerId: "stone-3",
    hint: "点一块就数一个：一、二、三。",
    successText: "一、二、三，卡车装好三块石头！",
    parentTip: "请孩子帮忙拿三个积木，一边拿一边数。",
    interests: ["construction", "vehicles"],
    interaction: { countGoal: 3 },
  },
  {
    id: "math-four-dino-eggs-m1",
    domain: "math",
    kind: "tap_count",
    skillId: "math.cardinality.1-4",
    difficulty: 2,
    ageBand: "36-42m",
    variantCount: 2,
    title: "四颗恐龙蛋回巢",
    skill: "1–4 点数",
    instruction: "点四颗蛋送回巢",
    spokenInstruction: "恐龙妈妈在等四颗蛋。点一点，慢慢数到四。",
    speechLang: "zh-CN",
    choices: [
      { id: "egg-1", label: "恐龙蛋", icon: "egg", color: "yellow" },
      { id: "egg-2", label: "恐龙蛋", icon: "egg", color: "green" },
      { id: "egg-3", label: "恐龙蛋", icon: "egg", color: "blue" },
      { id: "egg-4", label: "恐龙蛋", icon: "egg", color: "purple" },
      { id: "egg-5", label: "恐龙蛋", icon: "egg", color: "cream" },
    ],
    answerId: "egg-4",
    hint: "已经点过的蛋会亮起来，不要重复数。",
    successText: "一、二、三、四，四颗蛋都回家啦！",
    parentTip: "把四个玩具排成一排，用手指逐个点数。",
    interests: ["dinosaurs"],
    interaction: { countGoal: 4 },
  },
  {
    id: "math-sort-big-small-m1",
    domain: "math",
    kind: "drag_sort",
    skillId: "math.sort.size",
    difficulty: 2,
    ageBand: "36-42m",
    variantCount: 2,
    title: "恐龙按大小排队",
    skill: "按大小分类",
    instruction: "把大恐龙和小恐龙分开",
    spokenInstruction: "大大的恐龙去大脚印，小小的恐龙去小脚印。拖过去吧。",
    speechLang: "zh-CN",
    choices: [
      { id: "dino-big-1", label: "大恐龙", icon: "dinosaur", color: "green", visualScale: "large" },
      { id: "dino-small-1", label: "小恐龙", icon: "dinosaur", color: "yellow", visualScale: "small" },
      { id: "dino-big-2", label: "大恐龙", icon: "dinosaur", color: "blue", visualScale: "large" },
      { id: "dino-small-2", label: "小恐龙", icon: "dinosaur", color: "coral", visualScale: "small" },
    ],
    answerId: "dino-big-1",
    hint: "大恐龙身体高，小恐龙身体矮。",
    successText: "大小分清楚，恐龙队伍排好啦！",
    parentTip: "用两种大小的积木做一次分类。",
    interests: ["dinosaurs"],
    interaction: {
      targets: [
        { id: "big-bin", label: "大大的", icon: "foot", color: "green" },
        { id: "small-bin", label: "小小的", icon: "foot", color: "yellow" },
      ],
      correctTargets: {
        "dino-big-1": "big-bin",
        "dino-small-1": "small-bin",
        "dino-big-2": "big-bin",
        "dino-small-2": "small-bin",
      },
    },
  },
  {
    id: "math-sort-rocket-colors-m1",
    domain: "math",
    kind: "drag_sort",
    skillId: "math.sort.color",
    difficulty: 1,
    ageBand: "30-36m",
    variantCount: 2,
    title: "火箭按颜色进站",
    skill: "按颜色分类",
    instruction: "把红色和蓝色分开",
    spokenInstruction: "红色火箭去红色站，蓝色火箭去蓝色站。按颜色分一分。",
    speechLang: "zh-CN",
    choices: [
      { id: "rocket-red-1", label: "红火箭", icon: "rocket", color: "coral" },
      { id: "rocket-blue-1", label: "蓝火箭", icon: "rocket", color: "blue" },
      { id: "rocket-red-2", label: "红火箭", icon: "rocket", color: "coral" },
      { id: "rocket-blue-2", label: "蓝火箭", icon: "rocket", color: "blue" },
    ],
    answerId: "rocket-red-1",
    hint: "看火箭身后的颜色，再找一样颜色的站。",
    successText: "红色一队，蓝色一队，火箭进站！",
    parentTip: "收积木时选两种颜色分开放。",
    interests: ["space"],
    interaction: {
      targets: [
        { id: "red-station", label: "红色站", icon: "red", color: "coral" },
        { id: "blue-station", label: "蓝色站", icon: "blue", color: "blue" },
      ],
      correctTargets: {
        "rocket-red-1": "red-station",
        "rocket-blue-1": "blue-station",
        "rocket-red-2": "red-station",
        "rocket-blue-2": "blue-station",
      },
    },
  },
  {
    id: "math-car-under-bridge-m1",
    domain: "math",
    kind: "place_in_scene",
    skillId: "math.spatial.under",
    difficulty: 1,
    ageBand: "30-36m",
    variantCount: 2,
    title: "汽车开到桥下面",
    skill: "理解上面与下面",
    instruction: "把汽车停在桥下面",
    spokenInstruction: "小汽车要躲雨，请把它停在大桥下面。",
    speechLang: "zh-CN",
    choices: [
      { id: "car-place", label: "小汽车", icon: "car", color: "coral" },
    ],
    answerId: "car-place",
    hint: "桥下面有遮雨的地方。",
    successText: "汽车停在桥下面，不会淋雨啦！",
    parentTip: "把玩具放到椅子上面和下面各一次。",
    interests: ["vehicles", "construction"],
    interaction: {
      targets: [
        { id: "above-bridge", label: "桥上面", icon: "bridge", color: "yellow" },
        { id: "under-bridge", label: "桥下面", icon: "bridge", color: "blue" },
      ],
      correctTargets: { "car-place": "under-bridge" },
    },
  },
  {
    id: "math-shape-garages-m1",
    domain: "math",
    kind: "drag_match",
    skillId: "math.geometry.match",
    difficulty: 1,
    ageBand: "30-36m",
    variantCount: 2,
    title: "形状汽车找车库",
    skill: "匹配基本形状",
    instruction: "把形状送进一样的车库",
    spokenInstruction: "圆形找圆形，方形找方形，三角形找三角形。拖进一样的车库。",
    speechLang: "zh-CN",
    choices: [
      { id: "shape-circle", label: "圆形", icon: "circle", color: "blue" },
      { id: "shape-square", label: "方形", icon: "square", color: "yellow" },
      { id: "shape-triangle", label: "三角形", icon: "triangle", color: "green" },
    ],
    answerId: "shape-circle",
    hint: "看一看边和角，找到长得一样的形状。",
    successText: "三个形状都找到一样的车库啦！",
    parentTip: "转一转手里的方形积木，它还是方形。",
    interests: ["vehicles", "construction"],
    interaction: {
      targets: [
        { id: "circle-garage", label: "圆形车库", icon: "circle", color: "blue" },
        { id: "square-garage", label: "方形车库", icon: "square", color: "yellow" },
        { id: "triangle-garage", label: "三角车库", icon: "triangle", color: "green" },
      ],
      correctTargets: {
        "shape-circle": "circle-garage",
        "shape-square": "square-garage",
        "shape-triangle": "triangle-garage",
      },
    },
  },
  {
    id: "math-extend-track-pattern-m1",
    domain: "math",
    kind: "pattern_extend",
    skillId: "math.pattern.ab",
    difficulty: 2,
    ageBand: "36-42m",
    variantCount: 2,
    title: "修好双色轨道",
    skill: "延伸 AB 规律",
    instruction: "红、蓝、红，空位放什么？",
    spokenInstruction: "轨道是红色、蓝色、红色。接下来请放一块蓝色。",
    speechLang: "zh-CN",
    sceneIcons: ["red", "blue", "red"],
    sceneLabel: "红、蓝、红、？",
    choices: [
      { id: "pattern-blue", label: "蓝色", icon: "blue", color: "blue" },
      { id: "pattern-yellow", label: "黄色", icon: "yellow", color: "yellow" },
      { id: "pattern-green", label: "绿色", icon: "green", color: "green" },
    ],
    answerId: "pattern-blue",
    hint: "颜色在轮流出现：红、蓝、红……",
    successText: "红蓝红蓝，轨道接好啦！",
    parentTip: "用两种颜色的积木继续排 AB 规律。",
    interests: ["vehicles", "construction"],
    interaction: {
      targets: [{ id: "pattern-gap", label: "轨道空位", icon: "bridge", color: "cream" }],
      correctTargets: { "pattern-blue": "pattern-gap" },
    },
  },
  {
    id: "math-rocket-height-order-m1",
    domain: "math",
    kind: "sequence_3",
    skillId: "math.measure.order",
    difficulty: 2,
    ageBand: "36-42m",
    variantCount: 2,
    title: "火箭从矮到高",
    skill: "按高矮排序",
    instruction: "把火箭从矮到高排好",
    spokenInstruction: "先放最矮的火箭，再放中间的，最后放最高的。",
    speechLang: "zh-CN",
    choices: [
      { id: "rocket-short", label: "矮火箭", icon: "rocket", color: "yellow", visualScale: "small" },
      { id: "rocket-middle", label: "中火箭", icon: "rocket", color: "blue", visualScale: "medium" },
      { id: "rocket-tall", label: "高火箭", icon: "rocket", color: "coral", visualScale: "large" },
    ],
    answerId: "rocket-short",
    hint: "从占地方最小的火箭开始。",
    successText: "矮、中、高，三艘火箭排整齐啦！",
    parentTip: "找三件高矮不同的物品排成一队。",
    interests: ["space"],
    interaction: {
      targets: [
        { id: "height-one", label: "最矮", helper: "第 1 个", color: "yellow" },
        { id: "height-two", label: "中间", helper: "第 2 个", color: "blue" },
        { id: "height-three", label: "最高", helper: "第 3 个", color: "coral" },
      ],
      correctTargets: {
        "rocket-short": "height-one",
        "rocket-middle": "height-two",
        "rocket-tall": "height-three",
      },
    },
  },
  {
    id: "math-more-leaves-m1",
    domain: "math",
    kind: "look_choose",
    skillId: "math.compare.more",
    difficulty: 2,
    ageBand: "36-42m",
    variantCount: 2,
    title: "哪边的叶子更多",
    skill: "比较多少",
    instruction: "哪一边的叶子更多？",
    spokenInstruction: "左边有三片叶子，右边有两片叶子。哪一边更多？",
    speechLang: "zh-CN",
    sceneIcons: ["leaf", "leaf", "leaf"],
    sceneLabel: "左边三片，右边两片",
    choices: [
      { id: "more-left", label: "三片叶子", helper: "更多", icon: "leaf", color: "green", visualScale: "large" },
      { id: "more-right", label: "两片叶子", helper: "更少", icon: "leaf", color: "yellow", visualScale: "small" },
      { id: "more-same", label: "一样多", icon: "circle", color: "cream" },
    ],
    answerId: "more-left",
    hint: "三比二多一个。",
    successText: "三片比两片更多！",
    parentTip: "用两小堆水果比较哪一堆多。",
    interests: ["nature", "dinosaurs"],
  },

  // 英语：新增 9 个活动
  {
    id: "en-find-dinosaur-m1",
    domain: "english",
    kind: "listen_choose",
    skillId: "en.words.dinosaur",
    difficulty: 1,
    ageBand: "30-36m",
    variantCount: 2,
    title: "Find the dinosaur",
    skill: "听懂恐龙主题词",
    instruction: "Which one is a dinosaur?",
    spokenInstruction: "Dinosaur. Find the dinosaur.",
    speechLang: "en-US",
    choices: [
      { id: "en-dinosaur", label: "dinosaur", helper: "恐龙", icon: "dinosaur", color: "green" },
      { id: "en-dog", label: "dog", helper: "小狗", icon: "dog", color: "yellow" },
      { id: "en-car", label: "car", helper: "汽车", icon: "car", color: "coral" },
    ],
    answerId: "en-dinosaur",
    hint: "Dinosaur，背上有尖尖的骨板。",
    successText: "Yes! A dinosaur!",
    parentTip: "玩恐龙玩具时自然说一次 dinosaur。",
    interests: ["dinosaurs"],
  },
  {
    id: "en-find-bus-m1",
    domain: "english",
    kind: "listen_choose",
    skillId: "en.words.vehicles",
    difficulty: 1,
    ageBand: "30-36m",
    variantCount: 2,
    title: "Where is the bus?",
    skill: "听懂交通工具单词",
    instruction: "Where is the bus?",
    spokenInstruction: "Bus. A big bus. Where is the bus?",
    speechLang: "en-US",
    choices: [
      { id: "en-bus", label: "bus", helper: "公交车", icon: "bus", color: "yellow" },
      { id: "en-train", label: "train", helper: "火车", icon: "train", color: "green" },
      { id: "en-ship", label: "ship", helper: "轮船", icon: "ship", color: "blue" },
    ],
    answerId: "en-bus",
    hint: "Bus，城市里载很多人的大车。",
    successText: "Great! Here is the bus!",
    parentTip: "路上看到公交车时说“bus is coming”。",
    interests: ["vehicles"],
  },
  {
    id: "en-gifts-for-friends-m1",
    domain: "english",
    kind: "drag_match",
    skillId: "en.words.objects",
    difficulty: 2,
    ageBand: "36-42m",
    variantCount: 2,
    title: "Gifts for friends",
    skill: "理解三个熟悉名词",
    instruction: "Listen and match the gifts",
    spokenInstruction: "Leaf for the dinosaur. Apple for the rabbit. Ball for the dog.",
    speechLang: "en-US",
    choices: [
      { id: "en-leaf-gift", label: "leaf", helper: "叶子", icon: "leaf", color: "green" },
      { id: "en-apple-gift", label: "apple", helper: "苹果", icon: "apple", color: "coral" },
      { id: "en-ball-gift", label: "ball", helper: "皮球", icon: "ball", color: "blue" },
    ],
    answerId: "en-leaf-gift",
    hint: "Leaf 给 dinosaur，apple 给 rabbit，ball 给 dog。",
    successText: "Wonderful! Everyone has a gift!",
    parentTip: "今天只复用 leaf、apple、ball 中的一个词。",
    interests: ["dinosaurs", "animals"],
    interaction: {
      targets: [
        { id: "en-dino-target", label: "dinosaur", icon: "dinosaur", color: "green" },
        { id: "en-rabbit-target", label: "rabbit", icon: "rabbit", color: "yellow" },
        { id: "en-dog-target", label: "dog", icon: "dog", color: "blue" },
      ],
      correctTargets: {
        "en-leaf-gift": "en-dino-target",
        "en-apple-gift": "en-rabbit-target",
        "en-ball-gift": "en-dog-target",
      },
    },
  },
  {
    id: "en-sort-builder-tools-m1",
    domain: "english",
    kind: "drag_sort",
    skillId: "en.words.categories",
    difficulty: 2,
    ageBand: "36-42m",
    variantCount: 2,
    title: "Tools for the builder",
    skill: "理解工具与食物类别",
    instruction: "Tools here, food there",
    spokenInstruction: "Hammer, wrench and helmet are tools. Apple and banana are food. Sort them, please.",
    speechLang: "en-US",
    choices: [
      { id: "en-hammer", label: "hammer", helper: "锤子", icon: "hammer", color: "yellow" },
      { id: "en-wrench", label: "wrench", helper: "扳手", icon: "wrench", color: "blue" },
      { id: "en-helmet", label: "helmet", helper: "安全帽", icon: "helmet", color: "green" },
      { id: "en-apple", label: "apple", helper: "苹果", icon: "apple", color: "coral" },
      { id: "en-banana", label: "banana", helper: "香蕉", icon: "banana", color: "yellow" },
    ],
    answerId: "en-hammer",
    hint: "Tools 用来工作，food 可以吃。",
    successText: "Tools and food are sorted!",
    parentTip: "不用要求跟读，能按类别放对已经很好。",
    interests: ["construction"],
    interaction: {
      targets: [
        { id: "en-tools-bin", label: "tools", helper: "工具", icon: "wrench", color: "blue" },
        { id: "en-food-bin", label: "food", helper: "食物", icon: "apple", color: "yellow" },
      ],
      correctTargets: {
        "en-hammer": "en-tools-bin",
        "en-wrench": "en-tools-bin",
        "en-helmet": "en-tools-bin",
        "en-apple": "en-food-bin",
        "en-banana": "en-food-bin",
      },
    },
  },
  {
    id: "en-sun-moon-star-m1",
    domain: "english",
    kind: "listen_choose",
    skillId: "en.words.space",
    difficulty: 1,
    ageBand: "30-36m",
    variantCount: 2,
    title: "Sun, moon, star",
    skill: "听懂太空自然词汇",
    instruction: "Can you find the moon?",
    spokenInstruction: "Moon. The moon is in the night sky. Find the moon.",
    speechLang: "en-US",
    choices: [
      { id: "en-moon", label: "moon", helper: "月亮", icon: "moon", color: "purple" },
      { id: "en-sun", label: "sun", helper: "太阳", icon: "sun", color: "yellow" },
      { id: "en-star", label: "star", helper: "星星", icon: "star", color: "blue" },
    ],
    answerId: "en-moon",
    hint: "Moon，在夜晚天空里弯弯的。",
    successText: "Yes! The moon!",
    parentTip: "睡前看窗外时说一次 moon。",
    interests: ["space", "nature"],
  },
  {
    id: "en-big-green-dino-m1",
    domain: "english",
    kind: "place_in_scene",
    skillId: "en.phrase.adjectives",
    difficulty: 2,
    ageBand: "36-42m",
    variantCount: 2,
    title: "A big green dinosaur",
    skill: "理解大小和颜色组合",
    instruction: "Find the big green dinosaur",
    spokenInstruction: "A big green dinosaur. Put the big green dinosaur in the cave.",
    speechLang: "en-US",
    choices: [
      { id: "en-big-green", label: "big green", helper: "大大的绿色", icon: "dinosaur", color: "green", visualScale: "large" },
      { id: "en-small-yellow", label: "small yellow", helper: "小小的黄色", icon: "dinosaur", color: "yellow", visualScale: "small" },
      { id: "en-small-blue", label: "small blue", helper: "小小的蓝色", icon: "dinosaur", color: "blue", visualScale: "small" },
    ],
    answerId: "en-big-green",
    hint: "Big 是大大的，green 是绿色。",
    successText: "You found the big green dinosaur!",
    parentTip: "只在真实物品上复用 big 或 green 一个词。",
    interests: ["dinosaurs"],
    interaction: {
      targets: [{ id: "en-cave", label: "cave", helper: "山洞", icon: "stone", color: "cream" }],
      correctTargets: { "en-big-green": "en-cave" },
    },
  },
  {
    id: "en-car-in-box-m1",
    domain: "english",
    kind: "place_in_scene",
    skillId: "en.spatial.in",
    difficulty: 1,
    ageBand: "30-36m",
    variantCount: 2,
    title: "Put it in the box",
    skill: "听懂 in 和 out",
    instruction: "Put the car in the box",
    spokenInstruction: "Car in the box. Put the car in the box.",
    speechLang: "en-US",
    choices: [
      { id: "en-car-place", label: "car", helper: "汽车", icon: "car", color: "coral" },
    ],
    answerId: "en-car-place",
    hint: "In 是放进盒子里面。",
    successText: "The car is in the box!",
    parentTip: "收玩具时说一次“in the box”。",
    interests: ["vehicles", "construction"],
    interaction: {
      targets: [
        { id: "en-box-in", label: "in", helper: "盒子里面", icon: "box", color: "yellow" },
        { id: "en-box-out", label: "out", helper: "盒子外面", icon: "box", color: "blue" },
      ],
      correctTargets: { "en-car-place": "en-box-in" },
    },
  },
  {
    id: "en-good-morning-robot-m1",
    domain: "english",
    kind: "story_choice",
    skillId: "en.phrase.greeting",
    difficulty: 1,
    ageBand: "30-36m",
    variantCount: 2,
    title: "Good morning, robot",
    skill: "理解早晨问候",
    instruction: "早上见面说什么？",
    spokenInstruction: "The sun is up. The little robot wakes up. Good morning! What do we say?",
    speechLang: "en-US",
    choices: [
      { id: "en-good-morning", label: "Good morning!", helper: "早上好", icon: "sun", color: "yellow" },
      { id: "en-good-night", label: "Good night!", helper: "晚安", icon: "moon", color: "purple" },
      { id: "en-thank-you", label: "Thank you!", helper: "谢谢", icon: "thanks", color: "green" },
    ],
    answerId: "en-good-morning",
    hint: "太阳升起来、刚起床时说 Good morning。",
    successText: "Good morning, little robot!",
    parentTip: "明早第一次见面时自然说 Good morning。",
    interests: ["space", "construction"],
    interaction: {
      storyText: ["The sun is up.", "The little robot wakes up.", "It waves to you."],
    },
  },
  {
    id: "en-want-water-story-m1",
    domain: "english",
    kind: "story_choice",
    skillId: "en.phrase.needs",
    difficulty: 2,
    ageBand: "36-42m",
    variantCount: 2,
    title: "I want water",
    skill: "理解简单需求表达",
    instruction: "小恐龙口渴了，需要什么？",
    spokenInstruction: "The little dinosaur is thirsty. I want water. What does it need?",
    speechLang: "en-US",
    choices: [
      { id: "en-water", label: "water", helper: "水", icon: "cup", color: "blue" },
      { id: "en-apple-choice", label: "apple", helper: "苹果", icon: "apple", color: "coral" },
      { id: "en-ball-choice", label: "ball", helper: "皮球", icon: "ball", color: "yellow" },
    ],
    answerId: "en-water",
    hint: "Thirsty 是口渴，口渴时想喝 water。",
    successText: "Water, please. 小恐龙喝到水啦！",
    parentTip: "喝水时由家长示范一次“I want water”。",
    interests: ["dinosaurs", "nature"],
    interaction: {
      storyText: ["The dinosaur runs and jumps.", "Now it is thirsty.", "I want water."],
    },
  },
];
